languageCode = "ms-MY"
languageName = "Bahasa Melayu"
weight = 1
title = "Professional Runner Document Servis di Malaysia | MY Runner Document"

[params]
  displayName = "Bahasa Melayu"
  isoCode = "ms"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/runner_logo_transparent.png"
  description = "Perkhidmatan Runner Document Profesional Seluruh Malaysia"

[params.author]
  name = "MY Runner Document"
  email = "nuno@n9o.xyz"
  image = "img/runner_logo.png"
  headline = "Perkhidmatan Runner Document Profesional Seluruh Malaysia"
  bio = "Perkhidmatan Runner Document Profesional Seluruh Malaysia"
  links = [
    { whatsapp = "https://wa.me/601154220969" },
    { linkedin = "https://www.linkedin.com/company/movique-services/" }
  ]